name: Run Api tests

on:
  push:
    branches: [main]
    
jobs:
  cypress-run: 
   runs-on: ubuntu-latest
   steps:
    - name: Checkout
      uses: actions/checkout@v1
    
    # instalando as dependencias
    - run: npm install
    
    # executar os testes de Healthcheck
    - run: npm run test:healthcheck
    
    # executar os testes de Contract
    - run: npm run test:contract
    
    # executar os testes de Functional
    - run: npm run test:functional
