name: Run Api tests

on:
  push:
    branches: [main]
    
jobs:
  cypress-run: 
   runs-on: ubuntu-latest
   steps:
    - name: Checkout
      uses: actions/checkout@v1
    
    # instalando as dependencias
    - run: npm install
    
    # executar os testes de Healthcheck
    - run: npm run test:healthcheck
    
    # executar os testes de Contract
    - run: npm run test:contract
    
    # executar os testes de Functional
    - run: npm run test:functional

    - name: Upload Screenshots
      uses: actions/upload-artifact@v2.2.4
      if: failure()
      with:
        name: screenshots
        path: cypress/screenshots
    - name: Upload Videos
      uses: actions/upload-artifact@v2.2.4
      if: always()
      with:
        name: videos
        path: cypress/videos
